grid:
  alpha:
  - 0.5
  - 1.5
  gamma:
  - 0.5
  n_seeds: 1
  sigma_eta: 0.2
  target_N: 120
sprinkling:
  Ns:
  - 160
  - 240
  - 400
  T: 1.0
  dims:
  - 2
  - 3
  - 4
  - 5
  - 6
  seeds:
  - 0
  - 1
