name: CI (smoke)

on:
  push:
  pull_request:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Bench (CI config)
        run: make bench CONFIG=config/params_ci.yaml
      - name: Phase scan (CI config)
        run: make phase CONFIG=config/params_ci.yaml
      - name: Figures
        run: make figs
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: figs-out
          path: figs/out/*
