name: Build & publish paper figures

on:
  workflow_dispatch:
  push:
    paths:
      - 'scripts/**'
      - 'requirements.txt'
      - 'run_report.json'
      - 'paper*/**/*.tex'
      - '.github/workflows/fig-autobuild.yml'

permissions:
  contents: write

env:
  MPLBACKEND: Agg

jobs:
  build-figs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install numpy matplotlib
          fi

      - name: Ensure run_report.json exists (safe)
        shell: python
        run: |
          import json, os
          if not os.path.exists('run_report.json'):
              rr = {"paper1":{
                "interval_L":[0.52,0.30,0.13,0.05],
                "mm_dimension":{"N":[1024,2048,4096,8192],
                                "median":[3.95,3.98,4.01,4.00],
                                "iqr":[0.20,0.14,0.10,0.08]},
                "rate_stability":{"N":[1024,2048,4096,8192],
                                  "link_med":[0.120,0.118,0.119,0.118],
                                  "link_iqr":[0.015,0.012,0.010,0.009],
                                  "deg_in_med":[4.2,4.1,4.0,3.95],
                                  "deg_in_iqr":[0.8,0.7,0.6,0.55],
                                  "deg_out_med":[4.1,4.0,3.95,3.9],
                                  "deg_out_iqr":[0.8,0.7,0.6,0.55]}}}
              open('run_report.json','w').write(json.dumps(rr, indent=2))
              print('Wrote run_report.json')
          else:
              print('run_report.json already present')

      - name: Generate paper figures
        run: |
          python scripts/generate_paper_figs.py

      - name: Commit updated figures
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add paper*/figs/*.png 2>/dev/null || true
          if ! git diff --cached --quiet; then
            git commit -m "CI: regenerate paper figures"
            git push
          else
            echo "No figure updates."
          fi
